game.config.MAX_LEVELS = 15;

game.levels = [
    {
        background_package: "background_landofthedead",
        background_asset: "background_landofthedead",
        foreground_asset: "_landofthedead_foreground",
        level_package: "levels",
        level_asset: "level1",
    },
    {
        background_package: "background_landofthedead",
        background_asset: "background_landofthedead",
        foreground_asset: "_landofthedead_foreground",
        level_package: "levels",
        level_asset: "level3",
    },
    {
        background_package: "background_landofthedead",
        background_asset: "background_landofthedead",
        foreground_asset: "_landofthedead_foreground",
        level_package: "levels",
        level_asset: "level5",
    },
    {
        background_package: "background_landofthedead",
        background_asset: "background_landofthedead",
        foreground_asset: "_landofthedead_foreground",
        level_package: "levels",
        level_asset: "level2bis",
    },
    {
        background_package: "background_landofthedead",
        background_asset: "background_landofthedead",
        foreground_asset: "_landofthedead_foreground",
        level_package: "levels",
        level_asset: "level4bis",
    },
    {
        background_package: "background_landofthedead",
        background_asset: "background_landofthedead",
        foreground_asset: "_landofthedead_foreground",
        level_package: "levels",
        level_asset: "level6",
    },
    {
        background_package: "background_landofthedead",
        background_asset: "background_landofthedead",
        foreground_asset: "_landofthedead_foreground",
        level_package: "levels",
        level_asset: "level7",
    },
    {
        background_package: "background_nightosphere",
        background_asset: "background_nightosphere",
        foreground_asset: "_nightosphere_foreground",
        level_package: "levels_nightosphere",
        level_asset: "level1",
        fire: true,
    },
    {
        background_package: "background_nightosphere",
        background_asset: "background_nightosphere",
        foreground_asset: "_nightosphere_foreground",
        level_package: "levels_nightosphere",
        level_asset: "level2",
        fire: true,
    },
    {
        background_package: "background_nightosphere",
        background_asset: "background_nightosphere",
        foreground_asset: "_nightosphere_foreground",
        level_package: "levels_nightosphere",
        level_asset: "level3",
        fire: true,
    },
    {
        background_package: "background_nightosphere",
        background_asset: "background_nightosphere",
        foreground_asset: "_nightosphere_foreground",
        level_package: "levels_nightosphere",
        level_asset: "level4",
        fire: true,
    },
    {
        background_package: "background_nightosphere",
        background_asset: "background_nightosphere",
        foreground_asset: "_nightosphere_foreground",
        level_package: "levels_nightosphere",
        level_asset: "level5",
        fire: true,
    },
    {
        background_package: "background_nightosphere",
        background_asset: "background_nightosphere",
        foreground_asset: "_nightosphere_foreground",
        level_package: "levels_nightosphere",
        level_asset: "level6",
        fire: true,
    },
    {
        background_package: "background_nightosphere",
        background_asset: "background_nightosphere",
        foreground_asset: "_nightosphere_foreground",
        level_package: "levels_nightosphere",
        level_asset: "level7",
        fire: true,
    },
    {
        background_package: "background_end",
        background_asset: "background_end",
        foreground_asset: "_background_end_foreground",
        level_package: "levels_nightosphere",
        level_asset: "levelboss",
        mist: true
    },

];
