var SoundsConfig={bgm_menu:[{file:"bgm_menu",volume:.4,loop:-1}],bgm_ingame:[{file:"bgm_ingame",volume:.6,loop:-1}],button_click1:[{file:"button_click1",volume:.5}],button_click2:[{file:"button_click2",volume:.6}],button_boost:[{file:"button_click2",volume:.6}],button_over:[{file:"button_over",volume:.4}],fanfare_lose:[{file:"fanfare_lose",volume:1}],fanfare_win:[{file:"fanfare_win",volume:1}],lap1:[{file:"lap1",volume:1}],lap2:[{file:"lap2",volume:1}],race_intro:[{file:"race_intro",volume:1}],speed1:[{file:"speed1",
volume:.5}],speed2:[{file:"speed2",volume:.6}],speed3:[{file:"speed3",volume:.3}],speed4:[{file:"speed4",volume:.8}],boost1:[{file:"special_penelope",volume:.6}],boost2:[{file:"special_peter",volume:1}],boost3:[{file:"special_twosome",volume:.5}],boost4:[{file:"special_dastardly",volume:.7}],crash:[{file:"crash1",volume:.3},{file:"crash2",volume:.3},{file:"crash3",volume:.3}],item_box:[{file:"box_open",volume:.5}],item_glue:[{file:"box_glue",volume:.3}],item_oil:[{file:"box_oil",volume:.5}],item_spike:[{file:"box_spike",
volume:.9}]},MP3_Offsets={bgm_menu:{startOffset:25,endOffset:0},bgm_ingame:{startOffset:23,endOffset:0},button_click1:{startOffset:27,endOffset:0},button_click2:{startOffset:27,endOffset:0},button_over:{startOffset:27,endOffset:0},fanfare_lose:{startOffset:27,endOffset:0},fanfare_win:{startOffset:27,endOffset:0},lap1:{startOffset:27,endOffset:0},lap2:{startOffset:27,endOffset:0},race_intro:{startOffset:27,endOffset:0},speed1:{startOffset:27,endOffset:0},speed2:{startOffset:27,endOffset:0},speed3:{startOffset:27,
endOffset:0},speed4:{startOffset:27,endOffset:0},boost1:{startOffset:27,endOffset:0},boost2:{startOffset:27,endOffset:0},boost3:{startOffset:40,endOffset:0},boost4:{startOffset:27,endOffset:0},crash1:{startOffset:27,endOffset:0},crash2:{startOffset:27,endOffset:0},crash3:{startOffset:27,endOffset:0},box_open:{startOffset:27,endOffset:0},box_glue:{startOffset:27,endOffset:0},box_oil:{startOffset:27,endOffset:0},box_spike:{startOffset:27,endOffset:0}};var FPS=20,maxLaps=3,buildDateCfg={show:!0,font:"8px monospace",color:"grey",x:800,y:448,regX:1,regY:1},distanceToActivateMovement=10,maxRad=60,crashSpeed=25,BOOST={uses:1,turns:1,sfx:SoundsConfig.boost2,power:1.5},CRASH_STUN={uses:1,turns:1,sfx:SoundsConfig.boost4},OFF_ROAD={uses:1,turns:1,sfx:SoundsConfig.boost1},SHIELD={uses:1,turns:1,sfx:SoundsConfig.boost3,power:5},CarsConfig=[{spriteId:"car_1",soundId:"speed1",portraitId:"portrait_1",podiumId:"podium_character_1",radius:20,skill:OFF_ROAD},{spriteId:"car_2",
soundId:"speed2",portraitId:"portrait_2",podiumId:"podium_character_2",radius:20,skill:BOOST},{spriteId:"car_3",soundId:"speed3",portraitId:"portrait_3",podiumId:"podium_character_3",radius:20,skill:SHIELD},{spriteId:"car_4",soundId:"speed4",portraitId:"portrait_4",podiumId:"podium_character_4",radius:20,skill:CRASH_STUN}],TrackConfig=[{id:"track_1",scale:16,maxFriction:8,minFriction:3,bounceDamper:.1,impactRotation:20,rotationSpeed:130,spawnpointsList:[{x:221,y:83},{x:145,y:135},{x:86,y:216},{x:142,
y:277},{x:259,y:295},{x:380,y:353},{x:476,y:313},{x:588,y:368},{x:667,y:313},{x:722,y:260},{x:690,y:182},{x:733,y:132},{x:649,y:106},{x:530,y:78},{x:485,y:123},{x:407,y:86},{x:335,y:122}],waypointsList:[{x:100,y:152},{x:153,y:312},{x:578,y:360},{x:705,y:291},{x:693,y:111},{x:336,y:77}],sectorsPointList:[{x:202,y:106,b:40},{x:106,y:179,b:255},{x:172,y:295,b:45},{x:319,y:316,b:250},{x:468,y:326,b:50},{x:614,y:336,b:245},{x:689,y:266,b:55},{x:696,y:159,b:240},{x:647,y:94,b:60},{x:500,y:95,b:235},{x:339,
y:102,b:170}],gridTransformList:[{x:360,y:85,r:-2},{x:395,y:120,r:-2},{x:430,y:82,r:-3},{x:470,y:115,r:-2}]},{id:"track_2",scale:16,maxFriction:8,minFriction:3,bounceDamper:.1,impactRotation:20,rotationSpeed:130,spawnpointsList:[{x:589,y:352},{x:668,y:377},{x:695,y:283},{x:720,y:180},{x:600,y:148},{x:482,y:153},{x:406,y:229},{x:320,y:140},{x:211,y:90},{x:76,y:125},{x:108,y:223},{x:134,y:292},{x:268,y:275},{x:281,y:366},{x:364,y:343},{x:426,y:388}],waypointsList:[{x:715,y:339},{x:681,y:124},{x:405,
y:183},{x:124,y:68},{x:81,y:258},{x:309,y:331},{x:559,y:383}],sectorsPointList:[{x:615,y:370,b:40},{x:688,y:327,b:255},{x:706,y:249,b:45},{x:697,y:183,b:250},{x:641,y:129,b:50},{x:569,y:113,b:245},{x:508,y:152,b:55},{x:423,y:199,b:240},{x:326,y:164,b:60},{x:251,y:84,b:235},{x:152,y:80,b:65},{x:114,y:131,b:230},{x:105,y:215,b:70},{x:154,y:266,b:225},{x:232,y:280,b:75},{x:298,y:336,b:220},{x:379,y:355,b:80},{x:546,y:369,b:210}],gridTransformList:[{x:520,y:387,r:185},{x:490,y:351,r:185},{x:460,y:383,
r:185},{x:430,y:346,r:185}]},{id:"track_3",scale:7,maxFriction:1.9,minFriction:.9,bounceDamper:.5,impactRotation:450,rotationSpeed:330,spawnpointsList:[{x:571,y:126},{x:650,y:101},{x:714,y:146},{x:745,y:246},{x:727,y:340},{x:690,y:402},{x:652,y:312},{x:561,y:248},{x:492,y:343},{x:387,y:328},{x:293,y:327},{x:207,y:342},{x:234,y:179},{x:108,y:191},{x:97,y:113},{x:200,y:64},{x:320,y:138}],waypointsList:[{x:736,y:135},{x:732,y:382},{x:636,y:355},{x:617,y:242},{x:513,y:247},{x:419,y:341},{x:219,y:308},
{x:189,y:198},{x:62,y:134},{x:140,y:37},{x:295,y:76},{x:441,y:130}],sectorsPointList:[{x:647,y:119,b:70},{x:715,y:139,b:220},{x:734,y:214,b:65},{x:736,y:313,b:225},{x:697,y:387,b:60},{x:641,y:323,b:230},{x:564,y:239,b:55},{x:482,y:292,b:235},{x:350,y:339,b:50},{x:223,y:301,b:240},{x:179,y:185,b:45},{x:86,y:133,b:245},{x:118,y:62,b:40},{x:289,y:61,b:250},{x:375,y:123,b:35},{x:501,y:120,b:255}],gridTransformList:[{x:490,y:110,r:180},{x:460,y:140,r:180},{x:430,y:110,r:180},{x:400,y:140,r:180}]},{id:"track_4",
scale:16,maxFriction:8,minFriction:3,bounceDamper:.3,impactRotation:20,rotationSpeed:130,spawnpointsList:[{x:339,y:76},{x:217,y:79},{x:97,y:66},{x:106,y:157},{x:142,y:281},{x:188,y:151},{x:353,y:155},{x:324,y:368},{x:460,y:382},{x:441,y:140},{x:635,y:139},{x:635,y:276},{x:532,y:248},{x:568,y:378},{x:708,y:375},{x:740,y:280},{x:699,y:215},{x:732,y:139},{x:674,y:70},{x:598,y:39},{x:538,y:82},{x:477,y:38}],waypointsList:[{x:99,y:99},{x:91,y:220},{x:182,y:255},{x:224,y:170},{x:314,y:176},{x:347,y:336},
{x:444,y:334},{x:468,y:169},{x:583,y:168},{x:618,y:243},{x:545,y:327},{x:635,y:394},{x:734,y:340},{x:694,y:88},{x:345,y:38}],sectorsPointList:[{x:233,y:55,b:75},{x:163,y:68,b:215},{x:112,y:93,b:70},{x:96,y:152,b:220},{x:120,y:249,b:65},{x:190,y:215,b:225},{x:265,y:176,b:60},{x:343,y:303,b:230},{x:392,y:348,b:55},{x:453,y:216,b:235},{x:609,y:210,b:50},{x:551,y:323,b:240},{x:651,y:373,b:45},{x:717,y:309,b:245},{x:709,y:133,b:40},{x:653,y:76,b:250},{x:514,y:63,b:35},{x:378,y:62,b:255}],gridTransformList:[{x:390,
y:45,r:0},{x:420,y:75,r:0},{x:450,y:45,r:0},{x:480,y:75,r:0}]}];(function(){var b=window.utils=window.utils||{};b.savePrefix="";b.save=function(a,c){"undefined"!==typeof Storage&&("object"==typeof c&&(c=JSON.stringify(c)),localStorage.setItem(b.savePrefix+a,c))};b.load=function(a,c){if("undefined"!==typeof Storage){var d=localStorage.getItem(b.savePrefix+a);if(null==d)return c;switch(typeof c){case "number":return Number(d);case "boolean":return"true"==d;case "object":return JSON.parse(d);default:return d}}};b.clearSave=function(){if("undefined"!==typeof Storage)for(var b in localStorage)localStorage.removeItem(b)};
b.lerp=function(b,a,c){return(1-c)*b+c*a};b.easeOutCubic=function(b,a,c,g){return c*((b=b/g-1)*b*b+1)+a};b.playSound=function(a){return(a=b.randomElement(a))?createjs.Sound.play(a.file,a):null};b.mouseOverSound=null;b.setupSpriteButton=function(a,c,e,g,h,k){k=void 0===k?null:k;a.on("pressup",function(){(null==k||k())&&a.gotoAndPlay(c)});a.on("mouseout",function(){(null==k||k())&&a.gotoAndPlay(c)});a.on("mouseover",function(){if(null==k||k())a.gotoAndPlay(e),b.mouseOverSound&&b.playSound(b.mouseOverSound),
null!=h&&h(a)});a.on("mousedown",function(){(null==k||k())&&a.gotoAndPlay(g)})};b.buttonify=function(b,a,c){b.setBounds(a.x,a.y,a.width,a.height);b.hitArea=new createjs.Shape;c(b.hitArea.graphics);b.alpha=.5;b.on("mouseover",function(b){this.alpha=1},b);b.on("mouseout",function(b){this.alpha=.5},b)};b.createLabelButton=function(a,c){var d=new createjs.Text(a,c+"px monospace","#000"),f=d.getBounds();f.height+=5;b.buttonify(d,f,function(b){b.beginFill("#000");b.drawRect(f.x,f.y,f.width,f.height);b.endFill()});
return d};b.createLabeledButton=function(a,c,e){var d=new createjs.Container;d.label=new createjs.Text(a,e+"px monospace","#000");d.addChild(d.label);"string"==typeof c&&(c={button:c});a=d.label.getBounds().width;for(var f in c){var k=b.createLabelButton(c[f],e);k.x=a;d.addChild(k);d[f]=k;a+=k.getBounds().width}return d};b.makeTogglerFn=function(a,c,e,g){var d=function(d){a[c]=!a[c];b.save(g,a[c]);e.text=a[c]?"[ON]":"[OFF]"};b.load(g,!1)&&d({currentTarget:e});return d};b.format=function(){for(var b=
arguments[0],a=1;a<arguments.length;++a)b=b.replace("{"+(a-1)+"}",arguments[a]);return b};b.isPortrait=!1;var c=null,a=null;b.setupWindowsResize=function(d,f){a=f||document.querySelector("canvas");c=d;b.resizeCanvas();window.addEventListener("resize",b.resizeCanvas,!1)};b.resizeCanvas=function(){a.oncontextmenu=function(b){b.preventDefault()};var d=window.innerHeight,f=d*c;f>window.innerWidth&&(f=window.innerWidth,d=f/c);b.isPortrait=window.innerHeight>window.innerWidth;a.style.width=f+"px";a.style.height=
d+"px";a.style.marginBottom=(window.innerHeight-f)/2+"px";a.style.marginLeft=(window.innerWidth-f)/2+"px"};b.getUrlParameters=function(){for(var b,a=/\+/g,c=/([^&=]+)=?([^&]*)/g,g=window.location.search.substring(1),h={};b=c.exec(g);)h[decodeURIComponent(b[1].replace(a," "))]=decodeURIComponent(b[2].replace(a," "));return h};b.toStrRecurisve=function(a,c){var d;c=c||0;if("object"===typeof a){var f="";for(d=0;d<c;++d)f+="  ";d="\n"+f+"{\n";for(var h in a)d+=f+"  "+h+": "+b.toStrRecurisve(a[h],c+1);
d+=f+"}\n"}else d=a+"\n";return d};b.randomInt=function(b,a){return Math.floor(Math.random()*(a-b+1))+b};b.randomElement=function(a){return 1==a.length?a[0]:a[b.randomInt(0,a.length-1)]};b.convertNumberToSprites=function(b,a,c,g,h,k,l){for(var d=b,e=0==b?[0]:[];b<a&&0<d;)e[e.length]=d%10,d=Math.floor(d/10);b=0;for(a=c.length-1;0<=a;--a){var d=c[a],f;f=0==e.length?9:a>=e.length?0:e[a];d.gotoAndStop(k[f]);d.x=b;0<a&&(b+=h[f])}g.x=.5*(l-b)};b.playSound=function(a){return(a=b.randomElement(a))?createjs.Sound.play(a.file,
a):null}})();function Point(b,c){this.x=b||0;this.y=c||0}Point.prototype.set=function(b){this.x=b.x;this.y=b.y};Point.prototype.setXY=function(b,c){this.x=b;this.y=c};Point.prototype.squareDistance=function(b){return Math.pow(this.x-b.x,2)+Math.pow(this.y-b.y,2)};Point.prototype.rotate=function(b,c){var a=Math.cos(b),d=Math.sin(b),f=this.x*a-this.y*d,a=this.x*d+this.y*a;c=c||new Point;c.setXY(f,a);return c};Point.prototype.dot=function(b){return this.x*b.x+this.y+b.y};
Point.prototype.mirror=function(b){0>this.x&&(this.x=-this.x);var c=TempPointGet(b);c.scale(2*this.dot(b));this.substract(c)};Point.prototype.squareLength=function(){return this.x*this.x+this.y*this.y};Point.prototype.length=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};Point.prototype.distance=function(b){return Math.sqrt(this.squareDistance(b))};Point.prototype.clone=function(b){b=b||new Point;b.setXY(this.x,this.y);return b};
Point.prototype.normalize=function(){var b=this.length();0!=b&&(this.x/=b,this.y/=b)};Point.prototype.scale=function(b){this.x*=b;this.y*=b};Point.prototype.add=function(b){this.x+=b.x;this.y+=b.y};Point.prototype.substract=function(b){this.x-=b.x;this.y-=b.y};Point.prototype.angle=function(){return 180*Math.atan2(this.y,this.x)/Math.PI};var TempPointBuffer=[],TempPointIdx=0;function TempPointAlloc(b){for(;0!=--b;)TempPointBuffer.push(new Point)}
function TempPointGetXY(b,c){var a=TempPointBuffer[TempPointIdx++];TempPointIdx==TempPointBuffer.length&&(TempPointIdx=0);a.setXY(b,c);return a}function TempPointGet(b){return b?TempPointGetXY(b.x,b.y):TempPointGetXY(0,0)};var playerCar=null,cars=[],orderedCars=[],currentTrack=null,playerLaunchVector=new Point,onPause=!1,firstRace=utils.load("first_race",!0),carsAndFxContainer=new createjs.Container,uiForegroundContainer=new createjs.Container,trackContainer=new createjs.Container,gameContainer=new createjs.Container,lapCounterIds=["lap_1","lap_1","lap_2","lap_3","lap_3"],posCounterIds=["pos_1","pos_2","pos_3","pos_4"],lapCounterNo=null,posCounterNo=null,portrait=null,skillBtn=null,playerLaunchMeter=null,playerMarker=
null,timeToPodium=0,lights=null,lightsState=0,boostRestored=null,crashMap=[],landscape=new createjs.Container,itemTrigger=null,activeItems=[],TYPE_OIL=0,TYPE_SPIKE=1,TYPE_GLUE=2,TYPE_COUNT=2,oilPool=[],spikesPool=[],gluePool=[],fxPool=[],activeFxs=[],sparksAnim=["sparks_1","sparks_2","sparks_3"];
function initGame(){TempPointAlloc(250);var b=new createjs.Shape;b.graphics.beginFill("black");b.graphics.drawRect(0,0,stage.canvas.width,stage.canvas.height);b.addEventListener("click",function(){});b.alpha=.5;landscape.addChild(b,createSpritesheetItem("landscape","icon"));b=createSpritesheetItem("game_hud","btn_pause_idle");utils.setupSpriteButton(b,"btn_pause_idle","btn_pause_over","btn_pause_down");b.addEventListener("click",showPause);lapCounterNo=createSpritesheetItem("game_hud","lap_1");posCounterNo=
createSpritesheetItem("game_hud","pos_1");portrait=createSpritesheetItem("game_hud","portrait_1");skillBtn=createSpritesheetItem("game_hud","boost_on");skillBtn.addEventListener("click",function(b){utils.playSound(SoundsConfig.button_boost);utils.playSound(playerCar.skill.sfx);skillBtn.mouseEnabled=!1;activateSkill(playerCar);skillBtn.gotoAndPlay("boost_active")});lights=createSpritesheetItem("game_lights","idle");boostRestored=createSpritesheetItem("cars","+1_boost_end");uiForegroundContainer.addChild(createSpritesheetItem("game_hud",
"hud_bg"),b,lapCounterNo,posCounterNo,portrait,skillBtn,lights,boostRestored);gameContainer.addChild(trackContainer,carsAndFxContainer,uiForegroundContainer);playerMarker=createSpritesheetItem("game_hud","hud_circle");playerLaunchMeter=createSpritesheetItem("game_hud","hud_power");playerLaunchMeter.stop();for(b=0;b<CarsConfig.length;++b){crashMap.push([]);for(var c=0;c<CarsConfig.length;++c)crashMap[b].push(!1);var c=CarsConfig[b],a=c.car=new createjs.Sprite(ss.cars);a.podiumAnim=c.podiumId;a.idleAnim=
c.spriteId+"_idle";a.moveAnim=c.spriteId+"_move";a.skillOnAnim=c.spriteId+"_boost_on";a.skillIdleAnim=c.spriteId+"_boost_idle";a.skillActivateAnim=c.spriteId+"_boost_activate";a.skillOffAnim=c.spriteId+"_boost_off";a.speedSound=SoundsConfig[c.soundId];a.gotoAndPlay(a.idleAnim);a.velocity=new Point;a.radius=c.radius;a.skill=c.skill;a.skillTurns=c.skillTurns;a.hitArea=new createjs.Shape;c=a.getBounds();a.hitArea.graphics.beginFill("#000");a.hitArea.graphics.drawCircle(0,0,2*a.radius);a.hitArea.graphics.endFill();
a.getVelocityRatio=function(){return this.velocity.length()/this.maxVel}}for(b=0;b<TrackConfig.length;++b){var a=TrackConfig[b],d=createSpritesheetItem("track_masks",a.id),c=d.getBounds(),f=new createjs.Container;f.addChild(d);f.w=c.width;f.h=c.height;f.cache(0,0,f.w,f.h);f.ctx=f.cacheCanvas.getContext("2d");f.data=f.ctx.getImageData(0,0,f.w,f.h).data;f.removeChild(d);a.mask=f;a.background=createSpritesheetItem("track_bgs",a.id);a.foreground=createSpritesheetItem("track_fgs",a.id)}itemTrigger=createSpritesheetItem("cars",
"box_out_end");itemTrigger.radius=6;for(b=0;10>b;++b)fxPool.push(createSpritesheetItem("cars","sparks_1")),c=null,c=createSpritesheetItem("cars","oil_idle"),c.type=TYPE_OIL,c.radius=10,oilPool.push(c),c=createSpritesheetItem("cars","spikes_idle"),c.type=TYPE_SPIKE,c.radius=5,spikesPool.push(c),c=createSpritesheetItem("cars","glue_idle"),c.type=TYPE_GLUE,c.radius=5,gluePool.push(c)}function setupLights(){bgm_lights.play();bgm_lights.position=0;bgm_game.stop();bgm_game.position=0}
function startRace(b,c){firstRace?showTutorial():setupLights();0<=b&&(b>=TrackConfig.length&&(b=TrackConfig.length-1),currentTrack&&(trackContainer.removeChild(currentTrack.background),trackContainer.removeChild(currentTrack.mask),uiForegroundContainer.removeChild(currentTrack.foreground)),currentTrack=TrackConfig[b]);if(0<=c){cars.length=0;orderedCars.length=0;for(var a=currentTrack.gridTransformList.length-1,d=0;d<CarsConfig.length;++d){var f=CarsConfig[d],e=f.car;e.removeAllEventListeners();d===
c?(playerCar=e,cars.unshift(e),orderedCars.push(e),carsAndFxContainer.addChildAt(e,0),e.addEventListener("mousedown",mouseDown),e.addEventListener("pressmove",pressMove),e.addEventListener("pressup",mouseUp),portrait.gotoAndPlay(f.portraitId)):0<a&&(cars.push(e),orderedCars.push(e),carsAndFxContainer.addChild(e),--a)}}for(d=0;d<cars.length;++d)initCar(cars[d],currentTrack.gridTransformList[d],0==d);for(d=activeItems.length=0;d<currentTrack.spawnpointsList;++d)activeItems.push(null);skillBtn.gotoAndPlay("boost_on");
playerCar.skillRemainingUses=playerCar.skill.uses;playerCar.mouseEnabled=!1;skillBtn.mouseEnabled=!1;carsAndFxContainer.removeChild(playerMarker);lightsState=lights.alpha=0;trackContainer.addChild(currentTrack.background);uiForegroundContainer.addChildAt(currentTrack.foreground,0);lapCounterNo.gotoAndPlay("lap_1");if(debug){var a=function(b,a,c){var d=debug[a+"_POOL"];d||(d=debug[a+"_POOL"]=[]);for(var e=0;e<b.length;++e){if(e>=d.length){var f=new createjs.Text(a+e,"10px monospace",c);f.regX=f.getMeasuredWidth()/
2;f.regY=f.getMeasuredHeight()/2;d.push(f)}f=d[e];f.visible=!0;f.x=b[e].x;f.y=b[e].y;uiForegroundContainer.addChild(f)}for(;e<d.length;++e)d[e].visible=!1},d=function(b){b=b.target;var a=null;b==window.debug_SectorsButton&&window.debug_WaypointsButton?a=window.debug_WaypointsButton:b==window.debug_WaypointsButton&&window.debug_SectorsButton&&(a=window.debug_SectorsButton);if(l=!l)b.text_original=b.text,b.text="[END]",a&&(a.visible=!1),k.length=0,currentTrack.background.addEventListener("click",g),
b==window.debug_SectorsButton&&(trackContainer.addChild(currentTrack.mask),currentTrack.mask.alpha=1),carsAndFxContainer.visible=!1;else{b.text=b.text_original;a&&(a.visible=!0);currentTrack.mask.removeEventListener("click",g);trackContainer.removeChild(currentTrack.mask);carsAndFxContainer.visible=!0;var a="",c;for(c in k)a+="{ x: "+k[c].x+", y: "+k[c].y,b==window.debug_SectorsButton&&(a+=", b: "+k[c].b),a+=" },\n";console.log(a)}},g=function(b){b=Math.floor(stage.mouseX);var a=Math.floor(stage.mouseY),
c=getMaskIdx(currentTrack.mask,b,a);k.push({x:b,y:a,b:currentTrack.mask.data[c+2]})};if(debug.testRadCast){var h=new createjs.Shape;window.raycastOverlay=h;stage.addChild(h);stage.addEventListener("pressup",function(b){h.graphics.clear()});stage.addEventListener("pressmove",function(b){var a=TempPointGetXY(stage.mouseX,stage.mouseY),c=radcastMask(8,a,25),d=h.graphics;d.clear();if(0==b.nativeEvent.button){var e=TempPointGet(),f=TempPointGet();for(b=0;b<c.length;++b){var g=c[b];g["in"]?f.add(g.vec):
e.add(g.vec)}f.normalize();f.scale(15);e.normalize();e.scale(15);d.beginStroke("red");d.moveTo(a.x,a.y);d.lineTo(a.x+f.x,a.y+f.y);d.beginStroke("blue");d.moveTo(a.x,a.y);d.lineTo(a.x+e.x,a.y+e.y)}else if(1==b.nativeEvent.button)for(b=0;b<c.length;++b)g=c[b],g["in"]?d.beginStroke("red"):d.beginStroke("blue"),d.moveTo(g.pos.x,g.pos.y),d.lineTo(g.pos.x+g.vec.x,g.pos.y+g.vec.y);else{e=TempPointGet();for(b=0;b<c.length;++b)g=c[b],g["in"]||e.add(g.vec);c=TempPointGetXY(-10,100);d.beginStroke("red");d.moveTo(a.x,
a.y);d.lineTo(a.x+e.x,a.y+e.y);d.beginStroke("blue");d.moveTo(a.x,a.y);d.lineTo(a.x-c.x,a.y-c.y);e.normalize();c.mirror(e);c.scale(currentTrack.bounceDamper);d.beginStroke("green");d.moveTo(a.x,a.y);d.lineTo(a.x-c.x,a.y-c.y)}d.endFill()})}debug.skipLights&&(lightsState=2,bgm_lights.position=bgm_lights.duration);var k=[],l=!1;debug.setupSectors&&(window.debug_SectorsButton?window.debug_SectorsButton.removeAllEventListeners():window.debug_SectorsButton=utils.createLabelButton("[SECTORS]",28),uiForegroundContainer.addChild(window.debug_SectorsButton),
window.debug_SectorsButton.addEventListener("click",d));debug.setupWaypoints&&(window.debug_WaypointsButton?window.debug_WaypointsButton.removeAllEventListeners():window.debug_WaypointsButton=utils.createLabelButton("[WAYPOINTS]",28),uiForegroundContainer.addChild(window.debug_WaypointsButton),window.debug_SectorsButton&&(window.debug_WaypointsButton.y+=30),window.debug_WaypointsButton.addEventListener("click",d));debug.setupSpawnpoints&&(window.debug_SpawnButton?window.debug_SpawnButton.removeAllEventListeners():
window.debug_SpawnButton=utils.createLabelButton("[SPAWNPOINTS]",28),uiForegroundContainer.addChild(window.debug_SpawnButton),window.debug_SectorsButton&&(window.debug_SectorsButton.y+=30),window.debug_WaypointsButton&&(window.debug_SectorsButton.y+=30),window.debug_SpawnButton.addEventListener("click",d));debug.drawTrackMask&&(trackContainer.addChild(currentTrack.mask),currentTrack.mask.alpha=debug.drawTrackMask);debug.drawWaypoints&&a(currentTrack.waypointsList,"WP","green");debug.drawSectorPoints&&
a(currentTrack.sectorsPointList,"S","blue");debug.drawSpawnpoints&&a(currentTrack.spawnpointsList,"sp","red")}}
function endRace(){stage.removeChild(gameContainer);for(hidePause();0<activeFxs.length;){var b=activeFxs[activeFxs.length-1];carsAndFxContainer.removeChild(b);fxPool.push(b);--activeFxs.length}for(;0<activeItems.length;){if(b=activeItems[activeItems.length-1])switch(carsAndFxContainer.removeChild(b),b.type){case TYPE_OIL:oilPool.push(b);break;case TYPE_SPIKE:spikesPool.push(b);break;case TYPE_GLUE:gluePool.push(b)}--activeItems.length}}
function initCar(b,c,a){b.isPlayer=a;b.startTurn=a;b.x=c.x;b.y=c.y;b.rotation=c.r;b.initialRotation=c.r;b.isMoving=!1;b.laps=0;b.posIdx=0;b.velocity.setXY(0,0);b.distanceToNextSector=0;b.endTurnSpeed=0;b.maxVel=maxRad*currentTrack.scale;b.currentSectorIdx=currentTrack.sectorsPointList.length-1;b.stopRacing=!1;b.revolutions=0;b.boost=1;b.offRoad=!1;b.shieldStr=1;b.crashStun=!1;b.stunned=0;b.skillRemainingUses=b.skill.uses;b.skillRemainingTurns=0;b.skill.active=!1;b.gotoAndPlay(b.idleAnim)}
function beginPlayerTurn(){0<playerCar.stunned?(cars[1].startTurn=!0,playerCar.stunned=0):(playerCar.startTurn=!0,playerCar.mouseEnabled=!0,createjs.Touch.enable(playerCar),createjs.Touch.enable(stage),carsAndFxContainer.addChildAt(playerMarker,0),playerMarker.x=playerCar.x,playerMarker.y=playerCar.y);0>=playerCar.skillRemainingTurns&&(0<playerCar.skillRemainingUses?(skillBtn.gotoAndPlay("boost_on"),skillBtn.mouseEnabled=!0):skillBtn.gotoAndPlay("boost_off"));for(var b=0;b<CarsConfig.length;++b)for(var c=
0;c<CarsConfig.length;++c)crashMap[b][c]=!1;for(b=1;b<cars.length;++b)c=cars[b],0<c.stunned&&--c.stunned}function findSpawnItemIdx(){for(;;){var b=utils.randomInt(0,currentTrack.spawnpointsList.length-1);if(null==activeItems[b]){for(var c=!1,a=TempPointGet(currentTrack.spawnpointsList[b]),d=0;!c&&d<currentTrack.spawnpointsList.length;++d){var f=currentTrack.spawnpointsList[d];d!=b&&null!=f&&60>a.distance(f)&&(c=!0)}for(d=0;!c&&d<cars.length;d++)60>a.distance(cars[d])&&(c=!0);if(!c)return b}}}
function spawnItemTrigger(){var b=activeItems.indexOf(itemTrigger),c=findSpawnItemIdx();activeItems[c]=itemTrigger;itemTrigger.x=currentTrack.spawnpointsList[c].x;itemTrigger.y=currentTrack.spawnpointsList[c].y;itemTrigger.gotoAndPlay("box_in");carsAndFxContainer.addChild(itemTrigger);-1<b&&(activeItems[b]=null)}
function update(b){stage.update(b);if(utils.isPortrait)stage.contains(landscape)?stage.getChildIndex(landscape)!=stage.numChildren-1&&stage.setChildIndex(landscape,stage.numChildren-1):stage.addChild(landscape);else if(stage.contains(landscape)&&stage.removeChild(landscape),inGame&&!onPause)if(bgm_lights.position>bgm_lights.duration-100&&bgm_game.play(),5>lightsState)switch(lightsState){case 0:lights.alpha+=10*dt;1<=lights.alpha&&(lights.alpha=1,++lightsState,lights.gotoAndPlay("lights"));break;case 1:"lights_end"==
lights.currentAnimation&&++lightsState;break;case 2:lights.alpha-=10*dt,0>=lights.alpha&&(lights.alpha=0,lightsState=10,beginPlayerTurn(),spawnItemTrigger())}else{if(0<timeToPodium&&(carsAndFxContainer.removeChild(playerMarker),timeToPodium-=dt,0>=timeToPodium))switch(showPodium(orderedCars),playerCar.posIdx){case 0:case 1:utils.playSound(SoundsConfig.fanfare_win);break;default:utils.playSound(SoundsConfig.fanfare_lose)}for(b=activeFxs.length-1;0<=b;--b){var c=activeFxs[b];0<=c.currentAnimation.indexOf("end")&&
(carsAndFxContainer.removeChild(c),fxPool.push(c),--activeFxs.length)}for(b=0;b<cars.length;b++){var a=cars[b];if(a.startTurn)if(0!=b||debug&&debug.autoPlay){if(a.stopRacing)a.isMoving=!1,a.startTurn=!1;else{if(!a.isMoving){if(0>=a.stunned){a.gotoAndPlay(a.moveAnim);utils.playSound(a.speedSound);a.revolutions=0;for(var d,f,e=9999999999,c=TempPointGet(a),g=TempPointGet(),h=currentTrack.waypointsList.length-1;0<=h;h--){var k=currentTrack.waypointsList[h];d=c.distance(k);g.set(k);g.substract(a);d<e&&
!raycastMask(a,g)&&(f=h,e=d)}void 0==f?f=a.prevWPIdx:a.prevWPIdx=f;c=currentTrack.waypointsList[(f+1)%currentTrack.waypointsList.length];d=TempPointGetXY(c.x-a.x,c.y-a.y);c=d.length()*currentTrack.minFriction;d.normalize();d.scale(50);raycastMask(a,d)&&(e=d.rotate(.8,TempPointGet()),g=d.rotate(-.8,TempPointGet()),raycastMask(a,e)?raycastMask(a,g)||(d=g):d=e);d.normalize();a.velocity.set(d);a.offRoad||(g=getMaskIdx(currentTrack.mask,a.x,a.y),g=0==currentTrack.mask.data[g]?currentTrack.minFriction:
currentTrack.maxFriction,g!=currentTrack.minFriction&&(c*=2));c>a.maxVel&&(c=a.maxVel);a.velocity.scale(c);c=TempPointGetXY(a.x+a.velocity.x,a.y+a.velocity.y);a.rotation=180*Math.atan2(a.y-c.y,a.x-c.x)/Math.PI}a.isMoving=!0;a.initialRotation=a.rotation;a.endTurnSpeed=a.velocity.squareLength()/5}a.velocity.squareLength()<a.endTurnSpeed&&(a.isMoving=!1,a.startTurn=!1)}!a.startTurn&&b<cars.length-1&&(cars[b+1].startTurn=!0)}else a.isMoving&&a.velocity.squareLength()<a.endTurnSpeed&&(a.isMoving=!1,a.startTurn=
!1,cars[1].startTurn=!0)}for(b=f=0;b<cars.length;b++){a=cars[b];e=TempPointGet(a.velocity);e.scale(dt);if(isOut(a.x,a.y)){d=radcastMask(8,a,1.5*a.radius);g=TempPointGet();for(h=0;h<d.length;++h)c=d[h],c["in"]||g.add(c.vec);g.normalize();for(g.scale(2);isOut(a.x,a.y);)a.x+=g.x,a.y+=g.y}raycastMask(a,e)&&(a.velocity.length()>crashSpeed&&(spawnFx(a,a,utils.randomElement(sparksAnim)),utils.playSound(SoundsConfig.crash)),c=e.rotate(.8,TempPointGet()),raycastMask(a,c)?(c=e.rotate(-.8,TempPointGet()),raycastMask(a,
c)?(c=e.rotate(1.6,TempPointGet()),raycastMask(a,c)?(c=e.rotate(-1.6,TempPointGet()),raycastMask(a,c)?(e.x=-e.x,e.y=-e.y,a.velocity.x=-a.velocity.x,a.velocity.y=-a.velocity.y):(e=c,a.velocity.rotate(-1.6,a.velocity))):(e=c,a.velocity.rotate(1.6,a.velocity))):(e=c,a.velocity.rotate(-.8,a.velocity))):(e=c,a.velocity.rotate(.8,a.velocity)),a.revolutions=currentTrack.impactRotation*a.getVelocityRatio(),.5<Math.random()&&(a.revolutions=-a.revolutions),e.scale(currentTrack.bounceDamper),a.velocity.scale(currentTrack.bounceDamper));
d=TempPointGet(a);a.x+=e.x;a.y+=e.y;c=TempPointGet(a);a.isPlayer&&(playerLaunchMeter.x=a.x,playerLaunchMeter.y=a.y);a.offRoad?g=currentTrack.minFriction:(g=getMaskIdx(currentTrack.mask,a.x,a.y),g=0==currentTrack.mask.data[g]?currentTrack.minFriction:currentTrack.maxFriction);e.scale(g);a.velocity.substract(e);if(!a.stopRacing)for(e=0;e<activeItems.length;++e)if(g=activeItems[e])if(0<=g.currentAnimation.indexOf("end"))if(g==itemTrigger)spawnItemTrigger();else switch(carsAndFxContainer.removeChild(g),
activeItems[e]=null,g.type){case TYPE_OIL:oilPool.push(g);break;case TYPE_SPIKE:spikesPool.push(g);break;case TYPE_GLUE:gluePool.push(g)}else if(0<=g.currentAnimation.indexOf("idle")){h=a.radius+g.radius;k=TempPointGet(c);k.substract(d);var l=Math.ceil(k.length()/h),m=TempPointGet(d),n=!1;for(k.scale(1/l);0<l--;){if(h>m.distance(g)){n=!0;break}m.add(k)}if(n)switch(g.type){case TYPE_OIL:a.velocity.length()>crashSpeed&&(utils.playSound(SoundsConfig.item_oil),spawnFx(a,g,"oil_fx"),g=(.1+.1*Math.random())*
Math.PI,.5<Math.random()&&(g=2*Math.PI-g),a.velocity.rotate(g,a.velocity));break;case TYPE_SPIKE:utils.playSound(SoundsConfig.item_spike);g.gotoAndPlay("spikes_out");spawnFx(a,g,"spikes_fx");a.stunned=getStunLength();break;case TYPE_GLUE:a.velocity.length()>crashSpeed&&(utils.playSound(SoundsConfig.item_glue),g.gotoAndPlay("glue_out"),spawnFx(a,g,"glue_fx"),a.velocity.setXY(0,0));break;default:if(g==itemTrigger){utils.playSound(SoundsConfig.item_box);itemTrigger.gotoAndPlay("box_out");h=findSpawnItemIdx();
g=null;switch(utils.randomInt(0,TYPE_COUNT)){case TYPE_OIL:g=oilPool.pop();g.gotoAndPlay("oil_in");break;case TYPE_SPIKE:g=spikesPool.pop();g.gotoAndPlay("spikes_in");break;case TYPE_GLUE:g=gluePool.pop(),g.gotoAndPlay("glue_in")}activeItems[h]=g;g.x=currentTrack.spawnpointsList[h].x;g.y=currentTrack.spawnpointsList[h].y;carsAndFxContainer.addChildAt(g,0)}}}for(d=0;d<cars.length;d++)if(b!==d&&(e=cars[d],c.distance(e)<a.radius+e.radius)){!1===crashMap[b][d]&&(crashMap[b][d]=!0,a.velocity.length()+
e.velocity.length()>crashSpeed&&(TempPointGetXY(q,p).scale(.5),spawnFx(a,e,utils.randomElement(sparksAnim)),utils.playSound(SoundsConfig.crash)));var p=e.y-a.y,q=e.x-a.x,h=Math.atan2(p,q),g=.5*(a.x+Math.cos(h)*(a.radius+e.radius)-e.x),h=.5*(a.y+Math.sin(h)*(a.radius+e.radius)-e.y);1>=a.shieldStr?(e.crashStun&&(a.stunned=getStunLength(),e.currentAnimation!==e.skillActivateAnim&&e.gotoAndPlay(e.skillActivateAnim)),a.velocity.x-=g*e.shieldStr,a.velocity.y-=h*e.shieldStr):a.currentAnimation!==a.skillActivateAnim&&
a.gotoAndPlay(a.skillActivateAnim);1>=e.shieldStr?(a.crashStun&&(e.stunned=getStunLength(),a.currentAnimation!==a.skillActivateAnim&&a.gotoAndPlay(a.skillActivateAnim)),k=(a.getVelocityRatio()+e.getVelocityRatio())/2,e.velocity.x+=g*a.shieldStr,e.velocity.y+=h*a.shieldStr,e.revolutions=currentTrack.impactRotation*k*a.shieldStr,.5<Math.random()&&(e.revolutions=-e.revolutions)):e.currentAnimation!==e.skillActivateAnim&&e.gotoAndPlay(e.skillActivateAnim)}if(!a.stopRacing){f+=a.velocity.squareLength();
0<a.revolutions?(a.rotation+=a.revolutions*dt,a.revolutions-=dt*currentTrack.rotationSpeed,0>a.revolutions&&(a.revolutions=0)):0>a.revolutions&&(a.rotation-=a.revolutions*dt,a.revolutions+=dt*currentTrack.rotationSpeed,0<a.revolutions&&(a.revolutions=0));g=getMaskIdx(currentTrack.mask,a.x,a.y);c=currentTrack.mask.data[g+2];if(currentTrack.sectorsPointList[a.currentSectorIdx].b!=c)for(d=1;3>=d;++d)e=(a.currentSectorIdx+d)%currentTrack.sectorsPointList.length,currentTrack.sectorsPointList[e].b==c&&
(e<a.currentSectorIdx&&(++a.laps,a.isPlayer&&(1<a.laps&&a.laps<=maxLaps?(lapCounterNo.gotoAndPlay(lapCounterIds[a.laps]),utils.playSound(SoundsConfig.lap1),a.skillRemainingUses<a.skill.uses&&(a.skillRemainingUses=a.skill.uses,boostRestored.gotoAndPlay("+1_boost"))):a.laps>maxLaps&&utils.playSound(SoundsConfig.lap2))),a.currentSectorIdx=e);a.distanceToNextSector=TempPointGet(a).distance(currentTrack.sectorsPointList[a.currentSectorIdx]);a.isPlayer?(playerMarker.x=a.x,playerMarker.y=a.y,boostRestored.x=
a.x,boostRestored.y=a.y,a.laps>maxLaps&&0==a.isMoving&&(playerCar.mouseEnabled&&(playerCar.mouseEnabled=!1,skillBtn.mouseEnabled=!1),timeToPodium=2,a.laps=10,a.stopRacing=!0,a.removeAllEventListeners())):a.laps>maxLaps&&(a.laps=10,a.stopRacing=!0)}}500>f&&!playerCar.stopRacing&&!playerCar.startTurn&&(deactivateSkill(playerCar),beginPlayerTurn());orderedCars.sort(compareCarPosition);for(b=0;b<orderedCars.length;b++)a=orderedCars[b],a.posIdx=b,a.isPlayer&&a.laps<=maxLaps&&posCounterNo.gotoAndPlay(posCounterIds[a.posIdx])}}
function compareCarPosition(b,c){if(c.laps>b.laps)return 1;if(c.laps<b.laps)return-1;if(!b.stopRacing&&!c.stopRacing){if(c.currentSectorIdx>b.currentSectorIdx)return 1;if(c.currentSectorIdx<b.currentSectorIdx)return-1;if(c.distanceToNextSector<b.distanceToNextSector)return 1;if(c.distanceToNextSector>b.distanceToNextSector)return-1}return b.posIdx<c.posIdx?-1:b.posIdx>c.posIdx?1:0}
function mouseDown(b){carsAndFxContainer.addChild(playerLaunchMeter);playerLaunchMeter._goto("hud_power",0);playerLaunchMeter.x=playerCar.x;playerLaunchMeter.y=playerCar.y;playerCar.initialRotation=playerCar.rotation}
function pressMove(b){b=TempPointGet(gameContainer.globalToLocal(b.stageX,b.stageY));playerLaunchMeter.x=playerCar.x;playerLaunchMeter.y=playerCar.y;playerLaunchVector.x=playerCar.x-b.x;playerLaunchVector.y=playerCar.y-b.y;b=Math.min(playerLaunchVector.length(),maxRad)/maxRad*10;playerLaunchMeter._goto("hud_power",Math.floor(b));playerCar.rotation=playerLaunchMeter.rotation=playerLaunchVector.angle()+180}
function mouseUp(b){carsAndFxContainer.removeChild(playerLaunchMeter);b=playerLaunchVector.length();b<distanceToActivateMovement?playerCar.rotation=playerCar.initialRotation:(b>maxRad&&playerLaunchVector.scale(maxRad/b),playerCar.skill.active?playerCar.skill!==BOOST&&playerCar.skill!==OFF_ROAD||playerCar.gotoAndPlay(playerCar.skillActivateAnim):playerCar.gotoAndPlay(playerCar.moveAnim),playerLaunchVector.scale(currentTrack.scale*playerCar.boost),playerCar.velocity.set(playerLaunchVector),playerCar.isMoving=
!0,playerCar.mouseEnabled=!1,skillBtn.mouseEnabled=!1,playerCar.endTurnSpeed=playerCar.velocity.squareLength()/5,createjs.Touch.disable(stage),carsAndFxContainer.removeChild(playerMarker),utils.playSound(playerCar.speedSound))}
function activateSkill(b){if(0<b.skillRemainingUses)switch(--b.skillRemainingUses,b.skillRemainingTurns=b.skill.turns,b.skill.active=!0,b.gotoAndPlay(b.skillOnAnim),b.skill){case BOOST:b.boost=BOOST.power;break;case OFF_ROAD:b.offRoad=!0;break;case SHIELD:b.shieldStr=SHIELD.power;break;case CRASH_STUN:b.crashStun=!0}}
function deactivateSkill(b){if(0<b.skillRemainingTurns&&(--b.skillRemainingTurns,b.skill.active=!1,playerCar.skill!==BOOST&&playerCar.skill!==OFF_ROAD&&b.gotoAndPlay(b.skillOffAnim),0==b.skillRemainingTurns))switch(b.skill){case BOOST:b.boost=1;break;case OFF_ROAD:b.offRoad=!1;break;case SHIELD:b.shieldStr=1;break;case CRASH_STUN:b.crashStun=!1}}var raycastDeltaStep=new Point;
function raycastMask(b,c,a){a=void 0===a?null:a;var d=b.x;b=b.y;raycastDeltaStep.set(c);raycastDeltaStep.normalize();c=Math.round(c.length());var f=!1,e=!0;do{var g=isOut(d,b);if(null!=a){if(!e){var h=a[a.length-1];h["in"]==g?h.vec.add(raycastDeltaStep):e=!0}e&&(e={},e["in"]=g,e.pos=TempPointGetXY(d,b),e.vec=TempPointGet(),a.push(e),e=!1)}else if(g){f=!0;break}d+=raycastDeltaStep.x;b+=raycastDeltaStep.y}while(0<c--);return f}
function radcastMask(b,c,a){function d(a){f.push(a)}a=TempPointGetXY(a,0);for(var f=[],e=2*Math.PI/b;0<b--;){var g=[];raycastMask(c,a,g);g.forEach(d);a.rotate(e,a)}return f}function isOut(b,c){if(0>b||0>c||b>currentTrack.mask.w||c>currentTrack.mask.h)return!0;var a=getMaskIdx(currentTrack.mask,b,c),d=currentTrack.mask.data[a+1],f=currentTrack.mask.data[a+2];return 0===currentTrack.mask.data[a]&&0===d&&0===f}function getMaskIdx(b,c,a){return 4*(Math.floor(a)*b.w+Math.floor(c))}
function getStunLength(){return playerCar.startTurn?1:2}function spawnFx(b,c,a){var d=fxPool.pop();d&&(d.x=b.x+.5*(c.x-b.x),d.y=b.y+.5*(c.y-b.y),d.rotation=utils.randomInt(360),activeFxs.push(d),d.gotoAndPlay(a),carsAndFxContainer.addChild(d))};var mainMenu=new createjs.Container,selectCarMenu=new createjs.Container,selectTrackMenu=new createjs.Container,podiumMenu=new createjs.Container,pausePopup=new createjs.Container,tutorialPopup=new createjs.Container,overlay=new createjs.Shape,transition=new createjs.Shape,selectedCarIdx=utils.load("selected_car",0),currentMenu;function createSpritesheetItem(b,c){var a=new createjs.Sprite(ss[b]);a.gotoAndPlay(c);return a}var sfxToggles=[];
function registerSFXToggle(b){b.gotoAndStop(createjs.Sound.muted?"btn_sfx_off_idle":"btn_sfx_on_idle");b.stop();sfxToggles.push(b);null!=b.currentAnimation&&(b.on("pressup",function(){b.gotoAndPlay(createjs.Sound.muted?"btn_sfx_off_idle":"btn_sfx_on_idle")}),b.on("mouseout",function(){b.gotoAndPlay(createjs.Sound.muted?"btn_sfx_off_idle":"btn_sfx_on_idle")}),b.on("mouseover",function(){b.gotoAndPlay(createjs.Sound.muted?"btn_sfx_off_over":"btn_sfx_on_over");utils.playSound(SoundsConfig.button_over)}),
b.on("mousedown",function(){b.gotoAndPlay(createjs.Sound.muted?"btn_sfx_off_down":"btn_sfx_on_down")}));b.addEventListener("click",function(b){utils.playSound(SoundsConfig.button_click1);createjs.Sound.muted=!createjs.Sound.muted;utils.save("sound_muted",createjs.Sound.muted);b=createjs.Sound.muted?"btn_sfx_off_idle":"btn_sfx_on_idle";for(var a in sfxToggles)sfxToggles[a].gotoAndStop(b)})}
function initMenues(){createjs.Sound.muted=utils.load("sound_muted",!1);overlay.graphics.beginFill("black");overlay.graphics.drawRect(0,0,stage.canvas.width,stage.canvas.height);overlay.addEventListener("click",function(){});overlay.alpha=.5;transition.graphics.beginFill("black");transition.graphics.drawRect(0,0,stage.canvas.width,stage.canvas.height);transition.addEventListener("click",function(){});transition.alpha=0;(function(){var b=createSpritesheetItem("screen_main","btn_play_idle");utils.setupSpriteButton(b,
"btn_play_idle","btn_play_over","btn_play_down");b.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click2);showMenu(selectCarMenu)});var c=createSpritesheetItem("screen_main","btn_sfx_on_idle");registerSFXToggle(c);mainMenu.addChild(createSpritesheetItem("screen_main","background"),createSpritesheetItem("locale","logo"),b,c);buildDateCfg&&buildDateCfg.show&&(b=new createjs.Text(BUILD_DATE,buildDateCfg.font,buildDateCfg.color),b.x=buildDateCfg.x,b.y=buildDateCfg.y,b.regX=buildDateCfg.regX*
b.getMeasuredWidth(),b.regY=buildDateCfg.regY*b.getMeasuredHeight(),mainMenu.addChild(b))})();(function(){function b(a){var b=c[selectedCarIdx];selectedCarIdx+=a;0>selectedCarIdx&&(selectedCarIdx=CarsConfig.length-1);selectedCarIdx>=CarsConfig.length&&(selectedCarIdx=0);var d=c[selectedCarIdx];a=0<a?-350:350;d.x=-a;d.alpha=0;createjs.Tween.get(b).to({alpha:0,x:a},350,createjs.Ease.quadInOut);createjs.Tween.get(d).to({alpha:1,x:0},350,createjs.Ease.quadInOut);selectCarMenu.getChildIndex(d)<selectCarMenu.getChildIndex(b)&&
selectCarMenu.swapChildren(d,b)}for(var c=[],a=0;a<CarsConfig.length;++a){var d=createSpritesheetItem("locale",CarsConfig[a].spriteId);d.alpha=a==selectedCarIdx?1:0;c.push(d)}a=createSpritesheetItem("screen_select_car","btn_left_idle");utils.setupSpriteButton(a,"btn_left_idle","btn_left_over","btn_left_down");a.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click1);b(-1)});d=createSpritesheetItem("screen_select_car","btn_right_idle");utils.setupSpriteButton(d,"btn_right_idle",
"btn_right_over","btn_right_down");d.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click1);b(1)});var f=createSpritesheetItem("screen_select_car","btn_next_idle");utils.setupSpriteButton(f,"btn_next_idle","btn_next_over","btn_next_down");f.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click2);utils.save("selected_car",selectedCarIdx);showMenu(selectTrackMenu)});var e=createSpritesheetItem("screen_select_car","btn_back_idle");utils.setupSpriteButton(e,
"btn_back_idle","btn_back_over","btn_back_down");e.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click1);showMenu(mainMenu)});var g=createSpritesheetItem("screen_select_car","btn_sfx_on_idle");registerSFXToggle(g);selectCarMenu.addChild(createSpritesheetItem("screen_select_car","background"),createSpritesheetItem("locale","select_car_title"));createjs.Container.prototype.addChild.apply(selectCarMenu,c);selectCarMenu.addChild(g,a,d,e,f)})();(function(){var b=createSpritesheetItem("screen_select_track",
"btn_track_1_idle");utils.setupSpriteButton(b,"btn_track_1_idle","btn_track_1_over","btn_track_1_down");b.addEventListener("click",function(a){closeMenuStartRace(0,selectedCarIdx)});var c=createSpritesheetItem("screen_select_track","btn_track_2_idle");utils.setupSpriteButton(c,"btn_track_2_idle","btn_track_2_over","btn_track_2_down");c.addEventListener("click",function(a){closeMenuStartRace(1,selectedCarIdx)});var a=createSpritesheetItem("screen_select_track","btn_track_3_idle");utils.setupSpriteButton(a,
"btn_track_3_idle","btn_track_3_over","btn_track_3_down");a.addEventListener("click",function(a){closeMenuStartRace(2,selectedCarIdx)});var d=createSpritesheetItem("screen_select_track","btn_track_4_idle");utils.setupSpriteButton(d,"btn_track_4_idle","btn_track_4_over","btn_track_4_down");d.addEventListener("click",function(a){closeMenuStartRace(3,selectedCarIdx)});var f=createSpritesheetItem("screen_select_track","btn_back_idle");utils.setupSpriteButton(f,"btn_back_idle","btn_back_over","btn_back_down");
f.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click1);showMenu(selectCarMenu)});var e=createSpritesheetItem("screen_select_track","btn_sfx_on_idle");registerSFXToggle(e);selectTrackMenu.addChild(createSpritesheetItem("screen_select_track","background"),createSpritesheetItem("locale","select_track_title"),e,f,b,c,a,d)})();(function(){function b(a,b){var c=createSpritesheetItem("screen_podium","coord_1");c.x=a;c.y=b;podiumMenu.addChild(c);return c}var c=createSpritesheetItem("screen_podium",
"btn_next_idle");utils.setupSpriteButton(c,"btn_next_idle","btn_next_over","btn_next_down");c.addEventListener("click",closePodium);podiumMenu.addChild(createSpritesheetItem("screen_podium","podium_background"),c);podiumMenu.positions=[b(415,300),b(278,362),b(544,382)]})();(function(){var b=createSpritesheetItem("screen_pause","btn_help_idle");utils.setupSpriteButton(b,"btn_help_idle","btn_help_over","btn_help_down");b.addEventListener("click",showTutorial);var c=createSpritesheetItem("screen_pause",
"btn_close_idle");utils.setupSpriteButton(c,"btn_close_idle","btn_close_over","btn_close_down");c.addEventListener("click",function(){bgm_lights.paused=!1;bgm_game.paused=!1;utils.playSound(SoundsConfig.button_click1);hidePause()});var a=createSpritesheetItem("screen_pause","btn_restart_idle");utils.setupSpriteButton(a,"btn_restart_idle","btn_restart_over","btn_restart_down");a.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click2);startTransition(function(){endRace();stage.addChild(gameContainer);
startRace(-1,-1)})});var d=createSpritesheetItem("screen_pause","btn_select_idle");utils.setupSpriteButton(d,"btn_select_idle","btn_select_over","btn_select_down");d.addEventListener("click",function(a){utils.playSound(SoundsConfig.button_click2);inGame=!1;showMenu(selectCarMenu,!1,!0,endRace)});var f=createSpritesheetItem("screen_pause","btn_sfx_on_idle");registerSFXToggle(f);pausePopup.addChild(createSpritesheetItem("screen_pause","pause_background"),createSpritesheetItem("locale","pause_title"),
b,c,d,a,f)})();(function(){var b=createSpritesheetItem("screen_tutorial","btn_help_idle");utils.setupSpriteButton(b,"btn_help_idle","btn_help_over","btn_help_down");b.addEventListener("click",closeTutorial);tutorialPopup.addChild(createSpritesheetItem("screen_tutorial","tutorial_background"),createSpritesheetItem("locale","tutorial_title"),createSpritesheetItem("locale","tutorial_1"),createSpritesheetItem("locale","tutorial_2"),createSpritesheetItem("locale","tutorial_3"),createSpritesheetItem("screen_tutorial",
"tutorial_boost"),createSpritesheetItem("screen_tutorial","tutorial_control"),createSpritesheetItem("screen_tutorial","tutorial_traps"),b)})()}function showMenu(b,c,a,d){a=void 0===a?!0:a;d=void 0===d?null:d;c?(bgm_menu.stop(),stage.removeChild(currentMenu),stage.addChild(b),currentMenu=b):(c=function(){d&&d();stage.removeChild(currentMenu);stage.addChild(b);currentMenu=b},bgm_menu.play(),a?startTransition(c):c())}
function startTransition(b,c){stage.addChild(transition);transition.alpha=0;var a=createjs.Tween.get(transition);a.to({alpha:1},250,createjs.Ease.cubicIn);b&&a.call(b);a.call(function(){stage.addChild(transition)});a.to({alpha:0},250,createjs.Ease.cubicOut);a.call(function(){stage.removeChild(transition)});c&&a.call(c)}function showPause(){utils.playSound(SoundsConfig.button_click1);lights.paused=!0;bgm_lights.paused=!0;onPause=bgm_game.paused=!0;stage.addChild(overlay);showMenu(pausePopup,!0)}
function hidePause(){onPause=lights.paused=!1;stage.removeChild(pausePopup);stage.removeChild(overlay)}function showPodium(b){for(var c=0;3>c;++c)podiumMenu.positions[c].gotoAndPlay(b[c].podiumAnim);inGame=!1;showMenu(podiumMenu,!1,!0,function(){endRace();bgm_game.stop()})}function closePodium(b){utils.playSound(SoundsConfig.button_click2);showMenu(selectCarMenu)}
function closeMenuStartRace(b,c){utils.playSound(SoundsConfig.button_click2);startTransition(function(){stage.removeChild(currentMenu);stage.addChild(gameContainer);onPause=!1;inGame=!0;startRace(b,c);bgm_menu.stop()})}function showTutorial(){firstRace?showPause():utils.playSound(SoundsConfig.button_click1);showMenu(tutorialPopup,!0)}
function closeTutorial(){utils.playSound(SoundsConfig.button_click1);firstRace?(firstRace=!1,utils.save("first_race",firstRace),hidePause(),stage.removeChild(tutorialPopup),setupLights()):showMenu(pausePopup,!0)};var spritesheets_manifest=[{src:"images/cars.json",id:"cars"},{src:"images/main.json",id:"screen_main"},{src:"images/pause.json",id:"screen_pause"},{src:"images/select_car.json",id:"screen_select_car"},{src:"images/select_tracks.json",id:"screen_select_track"},{src:"images/podium.json",id:"screen_podium"},{src:"images/tutorial.json",id:"screen_tutorial"},{src:"images/locale.json",id:"locale"},{src:"images/landscape.json",id:"landscape"},{src:"images/hud.json",id:"game_hud"},{src:"images/lights.json",
id:"game_lights"},{src:"images/track_fgs.json",id:"track_fgs"},{src:"images/track_bgs.json",id:"track_bgs"},{src:"images/track_masks.json",id:"track_masks"}],images_manifest=[],audio_manifest=[];var debug=debug||!1,preloadContainer=new createjs.Container,queue=null,stage=null,images={},ss={},jsons={},dt=1/FPS,inGame=!1,bgm_lights,bgm_game,bgm_menu;
function init(){var b=document.getElementById("canvas");utils.setupWindowsResize(800/450,b);stage=new createjs.Stage(b);stage.enableMouseOver(15);createjs.Ticker.addEventListener("tick",update);createjs.Ticker.timingMode=createjs.Ticker.TIMEOUT;createjs.Ticker.setFPS(FPS);createjs.Ticker.maxDelta=50;queue=new createjs.LoadQueue(!0);queue.addEventListener("fileload",handleFileLoad);queue.addEventListener("complete",handlePreloadComplete);queue.loadFile({src:"images/loading.json",id:"preloader",type:"spritesheet"})}
function handlePreloadComplete(b){queue.removeEventListener("complete",handlePreloadComplete);b=new createjs.Shape;b.graphics.f("#863086").dr(0,0,stage.canvas.width,stage.canvas.height).ef();preloadContainer.addChild(b,createSpritesheetItem("preloader","loading_boomerang"),createSpritesheetItem("preloader","loading_bar_loop"));preloadContainer.addEventListener("click",function(){});stage.addChild(preloadContainer);queue.addEventListener("complete",handleSpritesheetsComplete);for(b=0;b<spritesheets_manifest.length;++b){var c=
spritesheets_manifest[b];c.type="json";c.is_spritesheet=!0;queue.loadFile(c,!1)}queue.load();createjs.Sound.alternateExtensions="mp3";queue.installPlugin(createjs.Sound);b=[];b.length=0;for(var a in SoundsConfig){var c=SoundsConfig[a],d;for(d in c){var f=c[d].file;f&&0>b.indexOf(f)&&(b.push(f),audio_manifest.push({src:"sounds/"+f+".ogg",type:"sound",id:f}))}}utils.mouseOverSound=SoundsConfig.button_over}
function handleSpritesheetsComplete(b){queue.removeEventListener("complete",handleSpritesheetsComplete);queue.addEventListener("complete",handleComplete);queue.loadManifest(images_manifest);queue.loadManifest(audio_manifest)}
function handleFileLoad(b){var c=b.item,a=b.result;if("sound"==b.item.type){if("mp3"==b.item.ext)for(var d in SoundsConfig){var c=SoundsConfig[d],f;for(f in c)if(a=c[f],a.file&&0<=b.item.src.indexOf(a.file)){var e=MP3_Offsets[a.file];0==e.endOffset?a.offset=e.startOffset:(a.startTime=e.startOffset,a.duration=1E3*b.result.duration-e.endOffset)}}}else if("spritesheet"==c.type)ss[c.id]=a;else if("json"==c.type){if(jsons[c.id]=a,c.is_spritesheet)for(a.is_spritesheet=!0,b=0;b<a.images.length;++b){d=a.images[b];
f=null;for(e=0;e<images_manifest.length;++e)if(images_manifest[e].src===d){f=images_manifest[e];break}null===f&&(f=d.lastIndexOf("."),e=d.lastIndexOf("/"),f={src:d,id:d.substring(e+1,f),ss_data:[]},images_manifest.push(f));f.ss_data.push({ss_id:c.id,img_idx:b})}}else if("image"==c.type&&(images[c.id]=a,c.ss_data))for(b=0;b<c.ss_data.length;++b)jsons[c.ss_data[b].ss_id].images[c.ss_data[b].img_idx]=a}
function handleComplete(b){queue=null;for(var c in jsons)jsons[c].is_spritesheet&&(ss[c]=new createjs.SpriteSheet(jsons[c]));bgm_lights=utils.playSound(SoundsConfig.race_intro);bgm_lights.stop();bgm_game=utils.playSound(SoundsConfig.bgm_ingame);bgm_game.stop();bgm_menu=utils.playSound(SoundsConfig.bgm_menu);bgm_menu.stop();initMenues();initGame();showMenu(mainMenu,!1,!1);debug&&debug.jumpToRace?closeMenuStartRace(debug.jumpToRace.trackIdx,debug.jumpToRace.carIdx):(stage.addChild(preloadContainer),
createjs.Tween.get(preloadContainer).to({alpha:0},500,createjs.Ease.quartOut).call(function(){stage.removeChild(preloadContainer);preloadContainer=null}))};
