var ge = ge || {};

WONBATS.addEnum(ge, [
    "KEY_DOWN",
    "KEY_UP",
    "ENEMY_DIE",
    "PLAYER_DIE",
    "PORTALS_OFF",
    "PORTALS_OFF_MID",
    "PORTALS_OFF_END",
    "CINNAMON_GONE",
    "CINNAMON_CASTS_BALLOONS",
    "WARP_IN",
    "WARP_OUT",
    "SHOCKWAVE",
    "LANDING_DUST",
    "FOOTPRINT_DUST",
    "FALLING_ROCKS",
    "STEP",
    "SPECTRAL_FIRE",
    "SPECTRAL_BUBBLES",
    "CREATE_BODY_PARTS",
    "SKELETON_HIT",
    "PLAYER_HIT",
    "SOUND_STEP",
    "SOUND_BREAK",

    "PAUSE_RESUME",
    "PAUSE_OUT",

    "ON_PAUSE",

    "SPLASH",
    "VOLCANO",
    "SNOT_HIT",
    "SNOT_LAUNCH",

    "GAMEOVER_IN",
    "GAMEOVER_OUT",

    "MM_READY",
    "LEVEL_SELECTION_IN",
    "LEVEL_SELECTION_OUT",
    "LEVEL_SELECTED",

    "CINNAMON_DEFEATED",
    "CINNAMON_REBORN",
    "CINNAMON_CLEAR",
    "LASER_HIT",

    "CREDITS",
    "C_OUT",
    "C_INPUT_ON",
    "C_INPUT_OFF",

]);
