export default 
{
    "audio": {
        "music": ["res/audio/music/SO-BB-Watering.mp3", "res/audio/music/SO-BG-outdoors-02.mp3", "res/audio/music/SO-intro-alt.mp3", "res/audio/music/SO-OB-watercan-soft.mp3", "res/audio/music/SO-OB-watercan.mp3"],
        "sfx": ["res/audio/sfx/AirHorn-02.mp3", "res/audio/sfx/silence.mp3", "res/audio/sfx/SO-99-sparklepow.mp3", "res/audio/sfx/SO-BB-18-Gong.mp3", "res/audio/sfx/SO-BB-Chainsaw-mix.mp3", "res/audio/sfx/SO-BB-FallHard-mix.mp3", "res/audio/sfx/SO-BB-Jackham-mix.mp3", "res/audio/sfx/SO-BB-jump.mp3", "res/audio/sfx/SO-Crow-Flap-Long.mp3", "res/audio/sfx/SO-DD-FallHard-mix.mp3", "res/audio/sfx/SO-DD-Paints-mix.mp3", "res/audio/sfx/SO-Falling-Whistle.mp3", "res/audio/sfx/SO-FruitHat.mp3", "res/audio/sfx/SO-FX-PotBreak.mp3", "res/audio/sfx/SO-GL-crumble-01.mp3", "res/audio/sfx/SO-GL-crumble-02.mp3", "res/audio/sfx/SO-GL-crunch.mp3", "res/audio/sfx/SO-GL-crunch2.mp3", "res/audio/sfx/SO-GL-drop-01.mp3", "res/audio/sfx/SO-GL-drop-02.mp3", "res/audio/sfx/SO-GL-drop-03.mp3", "res/audio/sfx/SO-GL-drop-04.mp3", "res/audio/sfx/SO-GL-pickup.mp3", "res/audio/sfx/SO-GL-pop.mp3", "res/audio/sfx/SO-GL-rattlegoal.mp3", "res/audio/sfx/SO-GL-splat-wet.mp3", "res/audio/sfx/SO-GrowFast-Down-1.mp3", "res/audio/sfx/SO-GrowFast-Up-2.mp3", "res/audio/sfx/SO-Gulp.mp3", "res/audio/sfx/SO-Hit-A.mp3", "res/audio/sfx/SO-Hit-B.mp3", "res/audio/sfx/SO-Hit-C.mp3", "res/audio/sfx/SO-Hit-D.mp3", "res/audio/sfx/SO-Hit-Metal-Gold.mp3", "res/audio/sfx/SO-Hit-Metal-Tin.mp3", "res/audio/sfx/SO-Hit-Metal.mp3", "res/audio/sfx/SO-Hit-Watermelon.mp3", "res/audio/sfx/SO-hole-win-sting.mp3", "res/audio/sfx/SO-LoungeSqueak.mp3", "res/audio/sfx/SO-Mask-Loop8.mp3", "res/audio/sfx/SO-OB-BirdBath.mp3", "res/audio/sfx/SO-OB-hitsplat.mp3", "res/audio/sfx/SO-OB-lounge-01.mp3", "res/audio/sfx/SO-OB-lounge-02.mp3", "res/audio/sfx/SO-OB-lounge-03.mp3", "res/audio/sfx/SO-OB-Shrine.mp3", "res/audio/sfx/SO-OB-spray-double.mp3", "res/audio/sfx/SO-OB-spray.mp3", "res/audio/sfx/SO-OB-supersizing.mp3", "res/audio/sfx/SO-PL-grow-mound.mp3", "res/audio/sfx/SO-PL-grow-spurt-h20.mp3", "res/audio/sfx/SO-PL-grow-spurt-tiny.mp3", "res/audio/sfx/SO-PL-grown-sparkle-01.mp3", "res/audio/sfx/SO-PL-grown-sparkle-02.mp3", "res/audio/sfx/SO-PL-RePotting.mp3", "res/audio/sfx/SO-PP-FallHard-mix.mp3", "res/audio/sfx/SO-PP-Sweep-mix.mp3", "res/audio/sfx/SO-RadioScratch.mp3", "res/audio/sfx/SO-Reject.mp3", "res/audio/sfx/SO-ricochet-A.mp3", "res/audio/sfx/SO-ricochet-B.mp3", "res/audio/sfx/SO-ricochet-C.mp3", "res/audio/sfx/SO-Seed-Rattle-01.mp3", "res/audio/sfx/SO-Seed-Rattle-02.mp3", "res/audio/sfx/SO-Seed-tiny-02.mp3", "res/audio/sfx/SO-SS-Eats-mix.mp3", "res/audio/sfx/SO-SS-FallHard-mix.mp3", "res/audio/sfx/SO-SuperClip-v3-mix.mp3", "res/audio/sfx/SO-Tap-BirdBath-1.mp3", "res/audio/sfx/SO-TC-drums-fadeout.mp3", "res/audio/sfx/SO-TD-FallHard-mix.mp3", "res/audio/sfx/SO-TD-SpinChew-mix.mp3", "res/audio/sfx/SO-TD-SpinDrag.mp3", "res/audio/sfx/SO-Trash.mp3", "res/audio/sfx/SO-WaterExplosion.mp3", "res/audio/sfx/TB-DropItem.mp3"]
    },
    "videos": [],
    "images": ["res/textures/nlt-gfug-0.png", "res/textures/nlt-gfug-1.png", "res/textures/nlt-gfug-2.png", "res/textures/nlt-gfug-3.png", "res/textures/preloader_1x.png", "res/textures/rotate_icon_white.png", "res/textures/TC-Artwork.png", "res/textures/TC-Background.png", "res/textures/TC-Button-Play.png", "res/textures/TC-Credits.png", "res/textures/TC-Logo.png", "res/textures/TC-Version.png", "res/textures/transition_circle_black.png", "res/textures/transition_pixel.png", "res/textures/UI-Sound-OFF.png", "res/textures/UI-Sound-ON.png", "res/textures/UI-Sound-QUIET.png"],
    "models": [],
    "spritesheets": ["res/textures/nlt-gfug-0.json", "res/textures/preloader_1x.json"]
}