export default {
    AUTO_DETECT_DEVICE_PIXEL_RATIO: true,
    LIGHTING_ENABLED: true,
    DIRECTIONAL_SHADOWS_ENABLED: true,
    POINT_SHADOWS_ENABLED: false,
    SHADOWS_VSM_ENABLED: false,
    DEFAULT_SHADOW_BIAS: 0.00002,
    MAX_BONES: 8,
    MAX_LIGHTS: 4
}